MAIN_FONT = "Stencil"
PATH_FONT = "Courier New"
# COLORS.
BLACK = "#000"
WHITE = "#FFF"
GREY = "#1F2937"
BLUE = "#1F6AA5"
DARK_GREY = "#4A4A4A"
CLOSE_RED = "#8A0606"
SLIDER_BG = "#64686B"
CANVAS_BG = "#242424"
DROPDOWN_MAIN = "#444"
DROPDOWN_HOVER = "#333"
DROPDOWN_MENU = "#666"
# DEFAULT POSITION.
DEFAULT_ROTATE = 0
DEFAULT_ZOOM = 0
FLIP_OPTIONS = ("NONE", "X", "Y", "BOTH")
# DEFAULT COLOR.
DEFAULT_GRAYSCALE = False
DEFAULT_INVERT = False
DEFAULT_BRIGHTNESS = 1
DEFAULT_VIBRANCE = 1
DEFAULT_SHARPNESS = 1
DEFAULT_COLOR_CONTRAST = 1
# DEFAULT EFFECT.
DEFAULT_BLUR = 0
DEFAULT_EFFECT_CONTRAST = 0
EFFECT_OPTIONS = (
    "NONE",
    "BLUR",
    "CONTOUR",
    "DETAIL",
    "EMBOSS",
    "EDGE ENHANCE",
    "FIND EDGES",
    "SMOOTH",
    "SHARPEN",
)
